### PR TITLE
Updated game to run on ggez crate 0.6.0

### PR DESCRIPTION
**Pull request by cowboy8625**
Just wanted to say you make some awesome clean code and this was so fun and educational to update this.   You may want to change some things that I did.

### CODE REVIEW

**Comment by cowboy8625** [comment]
welp I updated it again to `ggez v0.6.0-rs2`

**Review by fu5ha — CHANGES_REQUESTED** [review]
Sorry for not getting around to this originally! But thank you :D

**Comment by cowboy8625** [comment]
No worries.    I believe I commited the changes.

**Comment by cowboy8625** [comment]
updated `rand` and added `edition = "2018"` to `Cargo.toml` and also ran `cargo fmt` on file.

**Review by fu5ha — APPROVED** [review]

**Pull request merged**
